// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


namespace Portfolio.Models;

public partial class ViewHistory
{
    public int VId { get; set; }

    public string Ip { get; set; }

    public DateTime UtcDateTime { get; set; }
}